name: trader_pearl
author: valory
version: 0.1.0
description: A single-agent service (sovereign agent) placing bets on Omen, used by
  Pearl.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeibg7bdqpioh4lmvknw3ygnllfku32oca4eq5pqtvdrdsgw6buko7e
fingerprint_ignore_patterns: []
agent: valory/trader:0.1.0:bafybeihuzkr2gnkwuriaxqmxus7kdzviykzwov6cx6czbuvibgqlrtyqoe
number_of_agents: 1
deployment:
  agent:
    ports:
      0:
        8716: 8716
    volumes:
      ./data: /data
---
public_id: valory/trader_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        all_participants: []
        safe_contract_address: '0x0000000000000000000000000000000000000000'
        consensus_threshold: null
      drand_public_key: ${DRAND_PUBLIC_KEY:str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
      multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      service_id: ${SERVICE_ID:str:trader}
      service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x9338b5153AE39BB89f50468E608eD9d764B755fD}
      agent_registry_address: ${AGENT_REGISTRY_ADDRESS:str:0xE49CB081e8d96920C38aA7AB90cb0294ab4Bc8EA}
      use_acn_for_delivers: ${USE_ACN_FOR_DELIVERS:bool:false}
      sleep_time: ${SLEEP_TIME:int:1}
      tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
      tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
      tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
      creator_per_subgraph:
        omen_subgraph:
        - '0xFfc8029154ECD55ABED15BD428bA596E7D23f557'
      slot_count: ${SLOT_COUNT:int:2}
      opening_margin: ${OPENING_MARGIN:int:300}
      languages: ${LANGUAGES:list:["en_US"]}
      average_block_time: ${ABT:int:5}
      abt_error_mult: ${ABT_ERROR_MULT:int:5}
      mech_contract_address: ${MECH_CONTRACT_ADDRESS:str:0x77af31De935740567Cf4fF1986D04B2c964A786a}
      mech_request_price: ${MECH_REQUEST_PRICE:int:0}
      mech_chain_id: ${MECH_CHAIN_ID:str:gnosis}
      mech_wrapped_native_token_address: ${MECH_WRAPPED_NATIVE_TOKEN_ADDRESS:str:0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d}
      mech_activity_checker_contract: ${MECH_ACTIVITY_CHECKER_CONTRACT:str:0x155547857680A6D51bebC5603397488988DEb1c8}
      sample_bets_closing_days: ${SAMPLE_BETS_CLOSING_DAYS:int:10}
      trading_strategy: ${TRADING_STRATEGY:str:bet_amount_per_threshold}
      use_fallback_strategy: ${USE_FALLBACK_STRATEGY:bool:true}
      bet_threshold: ${BET_THRESHOLD:int:10000000000000000}
      ipfs_address: ${IPFS_ADDRESS:str:https://gateway.autonolas.tech/ipfs/}
      tools_accuracy_hash: ${TOOLS_ACCURACY_HASH:str:QmR8etyW3TPFadNtNrW54vfnFqmh8vBrMARWV76EmxCZyk}
      prompt_template: ${PROMPT_TEMPLATE:str:Please take over the role of a Data Scientist
        to evaluate the given question. With the given question "@{question}" and
        the `yes` option represented by `@{yes}` and the `no` option represented by
        `@{no}`, what are the respective probabilities of `p_yes` and `p_no` occurring?}
      dust_threshold: ${DUST_THRESHOLD:int:10000000000000}
      conditional_tokens_address: ${CONDITIONAL_TOKENS_ADDRESS:str:0xCeAfDD6bc0bEF976fdCd1112955828E00543c0Ce}
      realitio_proxy_address: ${REALITIO_PROXY_ADDRESS:str:0xAB16D643bA051C11962DA645f74632d3130c81E2}
      realitio_address: ${REALITIO_ADDRESS:str:0x79e32aE03fb27B07C89c0c568F80287C01ca2E57}
      event_filtering_batch_size: ${EVENT_FILTERING_BATCH_SIZE:int:5000}
      reduce_factor: ${REDUCE_FACTOR:float:0.25}
      max_filtering_retries: ${MAX_FILTERING_RETRIES:int:6}
      minimum_batch_size: ${MINIMUM_BATCH_SIZE:int:500}
      redeeming_batch_size: ${REDEEMING_BATCH_SIZE:int:1}
      slippage: ${SLIPPAGE:float:0.01}
      store_path: ./data
      policy_epsilon: ${POLICY_EPSILON:float:0.1}
      irrelevant_tools: ${IRRELEVANT_TOOLS:list:["prediction-offline", "prediction-online",
        "prediction-online-sme", "prediction-request-reasoning","native-transfer","prediction-online-lite","claude-prediction-online-lite","prediction-online-sme-lite","prediction-request-reasoning-lite","prediction-request-reasoning-claude-lite","prediction-request-rag","prediction-request-reasoning-claude","prediction-url-cot-claude","claude-prediction-offline","prediction-offline-sme","deepmind-optimization",
        "deepmind-optimization-strong", "openai-gpt-3.5-turbo", "openai-gpt-3.5-turbo-instruct",
        "openai-gpt-4", "openai-text-davinci-002", "openai-text-davinci-003", "prediction-online-sum-url-content",
        "prediction-online-summarized-info", "stabilityai-stable-diffusion-512-v2-1",
        "stabilityai-stable-diffusion-768-v2-1", "stabilityai-stable-diffusion-v1-5",
        "stabilityai-stable-diffusion-xl-beta-v2-2-2"]}
      staking_contract_address: ${STAKING_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
      disable_trading: ${DISABLE_TRADING:bool:false}
      stop_trading_if_staking_kpi_met: ${STOP_TRADING_IF_STAKING_KPI_MET:bool:true}
      agent_balance_threshold: ${AGENT_BALANCE_THRESHOLD:int:10000000000000000}
      refill_check_interval: ${REFILL_CHECK_INTERVAL:int:10}
      tool_punishment_multiplier: ${TOOL_PUNISHMENT_MULTIPLIER:int:1}
      redeem_round_timeout: ${REDEEM_ROUND_TIMEOUT:float:3600.0}
      contract_timeout: ${CONTRACT_TIMEOUT:float:300.0}
      blacklisting_duration: ${BLACKLISTING_DURATION:int:3600}
      file_hash_to_strategies: ${FILE_HASH_TO_STRATEGIES:dict:{"bafybeihufqu2ra7vud4h6g2nwahx7mvdido7ff6prwnib2tdlc4np7dw24":["bet_amount_per_threshold"],"bafybeibxfp27rzrfnp7sxq62vwv32pdvrijxi7vzg7ihukkaka3bwzrgae":["kelly_criterion_no_conf"]}}
      strategies_kwargs: ${STRATEGIES_KWARGS:dict:{"bet_kelly_fraction":1.5,"floor_balance":500000000000000000,"bet_amount_per_threshold":{"0.0":25000000000000000,"0.1":25000000000000000,"0.2":25000000000000000,"0.3":25000000000000000,"0.4":25000000000000000,"0.5":25000000000000000,"0.6":25000000000000000,"0.7":25000000000000000,"0.8":25000000000000000,"0.9":25000000000000000,"1.0":250000000000000000}}}
      mech_to_subscription_params: ${SUBSCRIPTION_PARAMS:dict:{"base_url":"https://marketplace-api.gnosis.nevermined.app/api/v1/metadata/assets/ddo",
        "did":"did:nv:01706149da2f9f3f67cf79ec86c37d63cec87fc148f5633b12bf6695653d5b3c",
        "escrow_payment_condition_address":"0x31B2D187d674C9ACBD2b25f6EDce3d2Db2B7f446",
        "lock_payment_condition_address":"0x2749DDEd394196835199471027713773736bffF2",
        "transfer_nft_condition_address":"0x659fCA7436936e9fe8383831b65B8B442eFc8Ea8",
        "token_address":"0x1b5DeaD7309b56ca7663b3301A503e077Be18cba", "order_address":"0x72201948087aE83f8Eac22cf7A9f2139e4cFA829",
        "nft_amount":"100", "payment_token":"0x0000000000000000000000000000000000000000",
        "price":"1000000000000000000"}}
      use_subgraph_for_redeeming: ${USE_SUBGRAPH_FOR_REDEEMING:bool:true}
      use_nevermined: ${USE_NEVERMINED:bool:false}
      use_mech_marketplace: ${USE_MECH_MARKETPLACE:bool:false}
      mech_marketplace_config: ${MECH_MARKETPLACE_CONFIG:dict:{"mech_marketplace_address":"0x0000000000000000000000000000000000000000","priority_mech_address":"0x0000000000000000000000000000000000000000","priority_mech_staking_instance_address":"0x0000000000000000000000000000000000000000","priority_mech_service_id":0,"requester_staking_instance_address":"0x0000000000000000000000000000000000000000","response_timeout":300}}
      policy_store_update_offset: ${POLICY_STORE_UPDATE_OFFSET:int:259200}
      expected_mech_response_time: ${EXPECTED_MECH_RESPONSE_TIME:int:300}
      mech_invalid_response: ${MECH_INVALID_RESPONSE:str:Invalid Response}
      mech_consecutive_failures_threshold: ${MECH_CONSECUTIVE_FAILURES_THRESHOLD:int:2}
      tool_quarantine_duration: ${TOOL_QUARANTINE_DURATION:int:18000}
      default_chain_id: ${DEFAULT_CHAIN_ID:str:gnosis}
  benchmark_tool:
    args:
      log_dir: /benchmarks
  network_subgraph:
    args:
      url: https://gnosis.subgraph.autonolas.tech
  omen_subgraph:
    args:
      url: https://omen.subgraph.autonolas.tech
  trades_subgraph:
    args:
      url: https://trades.subgraph.autonolas.tech
  conditional_tokens_subgraph:
    args:
      url: https://conditional-tokens.subgraph.autonolas.tech
  realitio_subgraph:
    args:
      url: https://realitio.subgraph.autonolas.tech
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://host.docker.internal:8545}
      chain_id: ${GNOSIS_LEDGER_CHAIN_ID:int:100}
      default_gas_price_strategy: ${GNOSIS_LEDGER_PRICING:str:eip1559}
      poa_chain: ${GNOSIS_LEDGER_IS_POA_CHAIN:bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: acn.staging.autonolas.tech:9005
    public_key: 02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: 02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77
  save_path: .certs/acn_cosmos_11000.txt
is_abstract: true
---
public_id: valory/http_server:0.22.0
type: connection
config:
  host: ${HTTP_SERVER_HOST:str:0.0.0.0}
  port: ${HTTP_SERVER_PORT:int:8716}
